### ISSUE TITLE
dls_barcode module missing?

### ISSUE THREAD

**Issue by HL-Evangelist** [DiamondLightSource/PuckBarcodeReader#82]
When executing the build.bat file, an error occurs on logconfig.py file (which is not copied into dls_barcode folder):

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import logconfig
  File "C:\Program Files\PuckScanner\PuckBarcodeReader-master\dls_barcode\logconfig.py", line 15, in <module>
    from dls_barcode import version
ImportError: cannot import name 'version'

A .exe file is produced but fails to open, with a 
Failed to execute script main
message

The command 
python main.py
also fails to execute

**Comment by UrszulaNeuman** [comment]
Hi, 
I don't think I ever seen this error and I could not reproduce it.
build.bat got updated within the latest release (1.6.0) and I used this updated version to create the .exe file attached to release 1.6.0. You could give it a try.
I was wondering if you remembered to activate the python virtual environment before running build .bat? That could explain your problems.
The same would apply to running 'python main.py'. You have to activate the python environment first.
Thanks,
Urszula
